select_preset_service:
  name: Set Preset
  description: Sets the preset by ID
  fields:
    device_id:
      name: Target Entity
      description: The entity to apply the preset to.
      required: true
      selector:
        device:
          integration: vogels_motion_mount_ble
    preset_id:
      name: Preset ID
      description: The numeric ID of the preset
      required: true
      selector:
        number:
          min: 0
          max: 7
          mode: box