refresh_data:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vogels_motion_mount_ble
disconnect:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vogels_motion_mount_ble
select_preset:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vogels_motion_mount_ble
    preset_id:
      required: true
      selector:
        select:
          translation_key: "preset_id"
          options:
            - "0"
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
            - "6"
delete_preset:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vogels_motion_mount_ble
    preset_id:
      required: true
      selector:
        select:
          translation_key: "preset_id"
          options:
            - "0"
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
            - "6"
set_preset:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vogels_motion_mount_ble
    preset_id:
      required: true
      selector:
        select:
          translation_key: "preset_id"
          options:
            - "0"
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
            - "6"
    name:
      required: true
      selector:
        text:
          multiline: false
    distance:
      required: true
      selector:
        number:
          min: 0
          max: 100
          step: 1
          mode: slider
    rotation:
      required: true
      selector:
        number:
          min: -100
          max: 100
          step: 1
          mode: slider
set_distance:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vogels_motion_mount_ble
    distance:
      required: true
      selector:
        number:
          min: 0
          max: 100
          step: 1
          mode: slider
set_rotation:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vogels_motion_mount_ble
    rotation:
      required: true
      selector:
        number:
          min: -100
          max: 100
          step: 1
          mode: slider
set_tv_width:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vogels_motion_mount_ble
    tv_width:
      required: true
      selector:
        text:
          multiline: false
set_automove:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vogels_motion_mount_ble
    automove_id:
      required: true
      selector:
        select:
          translation_key: "automove"
          options:
            - "off"
            - "hdmi_1"
            - "hdmi_2"
            - "hdmi_3"
            - "hdmi_4"
            - "hdmi_5"
set_freeze_preset:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vogels_motion_mount_ble
    preset_id:
      required: true
      selector:
        select:
          translation_key: "preset"
          options:
            - "0"
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
            - "6"
set_multi_pin_features:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vogels_motion_mount_ble
    multi_pin_feature_change_presets:
      required: true
      selector:
        boolean:
    multi_pin_feature_change_name:
      required: true
      selector:
        boolean:
    multi_pin_feature_disable_channel:
      required: true
      selector:
        boolean:
    multi_pin_feature_change_tv_on_off_detection:
      required: true
      selector:
        boolean:
    multi_pin_feature_change_default_position:
      required: true
      selector:
        boolean:
    multi_pin_feature_start_calibration:
      required: true
      selector:
        boolean:
set_name:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vogels_motion_mount_ble
    name:
      required: true
      selector:
        text:
          multiline: false
set_authorised_user_pin:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vogels_motion_mount_ble
    pin:
      required: true
      selector:
        text:
          multiline: false
set_supervisior_pin:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vogels_motion_mount_ble
    pin:
      required: true
      selector:
        text:
          multiline: false